// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtnNEvS8MaKv6bhnhh9AgnIlnTh5esTDE',
    appId: '1:781738479375:web:82f63c00286bb34bf3387a',
    messagingSenderId: '781738479375',
    projectId: 'vibzcheck-8fda7',
    authDomain: 'vibzcheck-8fda7.firebaseapp.com',
    databaseURL: 'https://vibzcheck-8fda7-default-rtdb.firebaseio.com',
    storageBucket: 'vibzcheck-8fda7.firebasestorage.app',
    measurementId: 'G-84TQ7R0CSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY61TUJRW7qfBZ8kNcYONfO4nVtYtJucY',
    appId: '1:781738479375:android:b99690ed923a383af3387a',
    messagingSenderId: '781738479375',
    projectId: 'vibzcheck-8fda7',
    databaseURL: 'https://vibzcheck-8fda7-default-rtdb.firebaseio.com',
    storageBucket: 'vibzcheck-8fda7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0p1_Bu3ENIPJi03bipTfdtzBPnCYbClE',
    appId: '1:781738479375:ios:ae6b9087a154889ef3387a',
    messagingSenderId: '781738479375',
    projectId: 'vibzcheck-8fda7',
    databaseURL: 'https://vibzcheck-8fda7-default-rtdb.firebaseio.com',
    storageBucket: 'vibzcheck-8fda7.firebasestorage.app',
    iosBundleId: 'com.vibzcheck.vibzcheck',
  );

}